# Generated by Django 4.0.5 on 2022-06-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
