# Generated by Django 4.2.2 on 2023-06-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Table Name')),
            ],
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('data_type', models.CharField(max_length=255, verbose_name='Data Type')),
                ('dynamic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.dynamicmodel')),
            ],
            options={
                'unique_together': {('dynamic_model', 'name')},
            },
        ),
    ]
