# Generated by Django 4.2.2 on 2023-07-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_dynamicmodel_fieldmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('dynamic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.dynamicmodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.fieldmodel')),
            ],
            options={
                'unique_together': {('dynamic_model', 'name')},
            },
        ),
    ]
