# Generated by Django 4.2.2 on 2023-07-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_valuemodel_unique_together_valuemodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuemodel',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Mapping code'),
        ),
    ]
